wordpress:
  image: wordpress:latest
  replicaCount: 1
  storage:
    size: 10Gi

mariadb:
  image: mariadb:latest
  replicaCount: 1
  storage:
    size: 10Gi
  rootPasswordLength: 16     # Integer, no decimal point
  userPasswordLength: 16     # Integer, no decimal point
  dbName: wordpress
  dbUser: wpuser

service:
  type: ClusterIP
  wordpressPort: 80
  mariadbPort: 3306

virtualService:
  hosts:
    - "example.com"

