{{- if .Values.postgres.enabled }}
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ .Values.postgres.name }}
spec:
  instances: {{ .Values.postgres.instances }}
  storage:
    size: {{ .Values.postgres.storage.size }}
  bootstrap:
    initdb:
      database: {{ .Values.postgres.bootstrap.initdb.database }}
      owner: {{ .Values.postgres.bootstrap.initdb.owner }}
{{- end }}
