apiVersion: v1
kind: Service
metadata:
  name: {{ include "mariadb.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "mariadb.fullname" . }}
  ports:
    - port: {{ .Values.service.mariadbPort }}
      targetPort: 3306
      protocol: TCP

