apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mariadb.fullname" . }}
type: Opaque
data:
  root-password: {{ randAlphaNum (int .Values.mariadb.rootPasswordLength) | b64enc }}
  db-user: {{ .Values.mariadb.dbUser | b64enc }}
  db-password: {{ randAlphaNum (int .Values.mariadb.userPasswordLength) | b64enc }}

