apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ include "wordpress.fullname" . }}
spec:
  hosts:
    {{- range .Values.virtualService.hosts }}
    - {{ . }}
    {{- end }}
  gateways:
    - istio-system/{{ include "wordpress.fullname" . }}-gateway
  http:
    - route:
        - destination:
            host: {{ include "wordpress.fullname" . }}
            port:
              number: {{ .Values.service.wordpressPort }}
